### Get all categories
GET http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json


### Create new categories
POST http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
    "name":"Network"
}

### Get category by Id
GET http://localhost:3000/api/categories/2
X-API-Key: RAHASIA
Accept: application/json

### Update category by Id
PUT http://localhost:3000/api/categories/2
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
    "name":"Minuman"
}

### Delete category by Id
DELETE  http://localhost:3000/api/categories/2
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json